### ISSUE TITLE
Footer change

### ISSUE THREAD

**Issue by Jocomol** [fujexo/landingpage-repo_mirror#42]
Hello for the new instance hosted on exoscale we need a new footer:

"A service operated by Adfinis (Adfinis Logo) and powered by Exoscale(Exoscale Logo)"

Thank you very much!

**Comment by c0rydoras** [comment]
For this please provide me with the logo to use, there might be some regulations etc.

> Exoscale logo and name are registered trademarks.
- https://www.exoscale.com/about-us/#download-brand-manual
